# config-defaults-60-40.yaml

experiment_tag:
  desc: "Tag for the experiment to differentiate configurations"
  value: "60_40__2"

train_corpora:
  desc: "Training corpora configurations"
  value:
    - dataset: "data/chall_mt/unprocessed/chall_dataset_second_split_v0"
      split: "train"
      load_from_disk: true
      target_duration_hours: 60
    - dataset: "data/chall_mt/processed/f5_synth_stt_dataset_v1"
      split: "train"
      load_from_disk: true
      target_duration_hours: 40

eval_corpora:
  desc: "Evaluation corpora configurations"
  value:
    - dataset: "data/chall_mt/unprocessed/chall_dataset_second_split_v0"
      split: "eval"
      load_from_disk: true
