experiment_name:
  desc: "Name of the experiment"
  value: "evaluation"

experiment_tag:
  desc: "Tag for identifying the experiment setup"
  value: "debug"

test_corpora:
  desc: "List of test corpora and their configurations"
  value:
    - dataset: "data/chall_mt/unprocessed/chall_dataset_second_split_v0"
      split: "test"
      load_from_disk: true

device:
  desc: "Device to run the experiment on (e.g., CPU, CUDA)"
  value: "cuda"

checkpoint:
  desc: "Path to the model checkpoint to be used"
  value: "train/train_5/chall_mt_train_60_80__5/best-checkpoint-0"

seed:
  desc: "Random seed for reproducibility"
  value: 123

wepr:
  desc: "Dont calculate wepr on synth data."
  value: False

eval_batch_size:
  desc: ""
  value: 4

eval_beam_size:
  desc: ""
  value: 100

min_word_count:
  desc: "Min number of words per sample. Make evaluation on samples with at least 3 words."
  value: 3
