experiment_name:
  desc: "Name of the experiment"
  value: "evaluation_real"

experiment_tag:
  desc: "Tag for identifying the experiment setup"
  value: "real"

test_corpora:
  desc: "List of test corpora and their configurations"
  value:
    - dataset: "data/chall_mt/unprocessed/chall_dataset_second_split_v0"
      split: "test"
      load_from_disk: true

checkpoint:
  desc: "Path to the model checkpoint to be used"
  value: "train/train_diff_data_portions/chall_mt_train_60_60/checkpoint-2700"

seed:
  desc: "Random seed for reproducibility"
  value: 123

eval_batch_size:
  desc: ""
  value: 4

eval_beam_size:
  desc: ""
  value: 100

min_word_count:
  desc: "Min number of words per sample. Make evaluation on samples with at least 3 words."
  value: 3