experiment_name:
  desc: "Name of the experiment"
  value: "evaluation_real"

experiment_tag:
  desc: "Tag for identifying the experiment setup"
  value: "real"

test_corpora:
  desc: "List of test corpora and their configurations"
  value:
    - dataset: "data/chall_mt/unprocessed/chall_dataset_v0"
      split: "eval"
      load_from_disk: true

device:
  desc: "Device to run the experiment on (e.g., CPU, CUDA)"
  value: "cuda"

checkpoint:
  desc: "Path to the model checkpoint to be used"
  value: "train/train_diff_data_portions/chall_mt_train_60_60/checkpoint-2700"

seed:
  desc: "Random seed for reproducibility"
  value: 123
