# config-defaults-20-0.yaml

experiment_tag:
  desc: "Tag for the experiment to differentiate configurations"
  value: "20_0"

train_corpora:
  desc: "Training corpora configurations"
  value:
    - dataset: "data/chall_mt/unprocessed/chall_dataset_v0"
      split: "train"
      load_from_disk: true
      target_duration_hours: 20
    - dataset: "data/chall_mt/processed/f5_synth_stt_dataset_v1"
      split: "train"
      load_from_disk: true
      target_duration_hours: 0
